{% set version = '1.2.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-matchthem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MatchThem_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MatchThem/MatchThem_{{ version }}.tar.gz
  sha256: 23420cf44cd573e274f9e59504fbc5e91af374f3138e055d7b0f433ba2546a8a

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matchit >=4.0.0
    - r-weightit
    - r-mice
    - r-rlang
    - r-survey
  run:
    - r-base
    - r-matchit >=4.0.0
    - r-weightit
    - r-mice
    - r-rlang
    - r-survey

test:
  commands:
    - $R -e "library('MatchThem')"           # [not win]
    - "\"%R%\" -e \"library('MatchThem')\""  # [win]

about:
  home: https://github.com/FarhadPishgar/MatchThem
  license: GPL-2.0-or-later
  summary: Provides essential tools for the pre-processing techniques of matching and weighting
    multiply imputed datasets. The package includes functions for matching within and
    across multiply imputed datasets using various methods, estimating weights for units
    in the imputed datasets using multiple weighting methods, calculating causal effect
    estimates in each matched or weighted dataset using parametric or non-parametric
    statistical models, and pooling the resulting estimates according to Rubin's rules
    (please see <https://journal.r-project.org/archive/2021/RJ-2021-073/> for more details).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: MatchThem
# Title: Matching and Weighting Multiply Imputed Datasets
# Description: Provides essential tools for the pre-processing techniques of matching and weighting multiply imputed datasets. The package includes functions for matching within and across multiply imputed datasets using various methods, estimating weights for units in the imputed datasets using multiple weighting methods, calculating causal effect estimates in each matched or weighted dataset using parametric or non-parametric statistical models, and pooling the resulting estimates according to Rubin's rules (please see <https://journal.r-project.org/archive/2021/RJ-2021-073/> for more details).
# Version: 1.2.1
# Authors@R: c(person("Farhad", "Pishgar", role = c("aut", "cre"), email = "Farhad.Pishgar@Gmail.com"), person("Noah", "Greifer", role = "aut", email = "noah.greifer@gmail.com"), person("Clemence", "Leyrat", role = "ctb", email = "Clemence.Leyrat@lshtm.ac.uk"), person("Elizabeth", "Stuart", role = "ctb", email = "estuart@jhu.edu"))
# Maintainer: Farhad Pishgar <Farhad.Pishgar@Gmail.com>
# Depends: R (>= 3.6.0)
# Imports: MatchIt (>= 4.0.0), mice, rlang, survey, WeightIt
# Suggests: Amelia, cobalt (>= 4.0.0), R.rsp
# URL: https://github.com/FarhadPishgar/MatchThem
# BugReports: https://github.com/FarhadPishgar/MatchThem/issues
# License: GPL (>= 2)
# Encoding: UTF-8
# LazyData: true
# VignetteBuilder: R.rsp
# RoxygenNote: 7.3.1
# NeedsCompilation: no
# Author: Farhad Pishgar [aut, cre], Noah Greifer [aut], Clemence Leyrat [ctb], Elizabeth Stuart [ctb]
# Packaged: 2024-04-01 23:33:01 UTC; farhadpishgar
# Repository: CRAN
# Date/Publication: 2024-04-02 00:30:02 UTC
